package com.myspace.order_management;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SupplierInfo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SupplierInfo() {
    }




}